GET http://localhost:3000/api/orders/

###

GET http://localhost:3000/api/orders/63dbb41d5fa2c088ee25afd7

###

POST http://localhost:3000/api/orders/
Content-Type: application/json

{
    "orderItems": 
        [{
        "product": "63d147469943c6c6e9ee22a3",
        "quantity": 1,
        "price": 150
        }, {
        "product": "63d147b99943c6c6e9ee22a6",
        "quantity": 1,
        "price": 500
        }],
    "deliveryAddress": 
        [{"street": "Shitgate",
        "city": "Shit Town",
        "zipcode": "222 22"
        }]
}

###

DELETE http://localhost:3000/api/orders/63d395d8dc8f803acfa2dd65

###