GET http://localhost:3000/api/orders/

###

GET http://localhost:3000/api/orders/5f4dab42c36a6d0c34e00000

###

POST http://localhost:3000/api/orders/
Content-Type: application/json

{
    "orderItems": 
        [{
        "product": "63d1134c26186b138766f23a",
        "quantity": 1,
        "price": 79
        }, {
        "product": "63d1091d575de550c5e14cf4",
        "quantity": 1,
        "price": 1200
        }],
    "deliveryAddress": 
        [{"street": "Shitgate",
        "city": "Shit Town",
        "zip": "222 22"
        }]
}

###

DELETE http://localhost:3000/api/orders/63d395d8dc8f803acfa2dd65

###