GET http://localhost:3000/api/orders/

###

GET http://localhost:3000/api/orders/63dbc4a60d3537ba5e9453d6

###

POST http://localhost:3000/api/orders/
Content-Type: application/json

{
    "orderItems": 
        [{
        "product": "63d147469943c6c6e9ee22a3",
        "quantity": 3
        }, {
        "product": "63d147b99943c6c6e9ee22a6",
        "quantity": 3
        }],
    "deliveryAddress": 
        [{"street": "Shitgate",
        "city": "Shit Town",
        "zipcode": "222 22"
        }]
}

###

PUT http://localhost:3000/api/orders/63dbc4a60d3537ba5e9453d5

###