GET http://localhost:3000/api/products/getAll

###

POST http://localhost:3000/api/products/newProduct
Content-Type: application/json

{
    "title": "Filmen 1",
    "description": "Jättebra!",
    "price": 100,
    "image":"Bild1",
    "inStock": 15
}

###