GET http://localhost:3000/api/products

###

GET http://localhost:3000/api/products/2390+1203933

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "title": "Title1",
    "description": "Desc1",
    "price": 499,
    "image": "image",
    "inStock": 100,
    "categories": ["63cd99b8940b3f7c0de63d52"]
}

### 
PUT http://localhost:3000/api/products/63cd9f1addac998418397a00
Content-Type: application/json

{
    "_id": "63cd9f1addac998418397a00",
    "title": "Title1",
    "description": "Desc1",
    "price": 499,
    "image": "https://user-images.githubusercontent.com/17639389/210451386-ac03b6e8-323b-4289-b526-28fdc156715a.jpg",
    "inStock": 100,
    "categories": ["63cd9df626c978a134484ec3"]
}